### ISSUE TITLE
Where are we on this?

### ISSUE THREAD

**Issue by benyanke** [benyanke/ZombieRepo-Java2Group#1]
Anyone know where we are on this? I'm looking to do part, but I can't do anything until someone does part 1...

**Comment by summersja05** [comment]
Why can't you do #2 until someone does #1? They're pretty much separate, aren't they? Even if the character factory isn't fully running yet, you can pretty much do #2 as-is and only test it with the parts that are working for now, can't you? (Note: I don't intend to come off as condescending, but it's hard to convey tone through text in a formal setting like this)

**Comment by HoushCE29** [comment]
Waiting on other classes to be made. But #2 can be done unreleased. Basically #1 can be released with the extra code for #2 commented out.

**Comment by benyanke** [comment]
Gotcha, I must have misunderstood the assignment. I'll look closer and check it out. Thanks @summersja05

**Comment by HoushCE29** [comment]
I added two methods that can be used to simplify making the extra output in version 2. It might also be a good idea to take the code in version 1 (the while loop i also added) and put it in a method so it too can be reused
